// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtXacVhUqfTNU0lC18iQPMAm5YWbUq1RA',
    appId: '1:394544889657:web:480d7a5e3b912188fb32e8',
    messagingSenderId: '394544889657',
    projectId: 'fooddelivery-81c3c',
    authDomain: 'fooddelivery-81c3c.firebaseapp.com',
    storageBucket: 'fooddelivery-81c3c.appspot.com',
    measurementId: 'G-LFH99JEXDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfi1PZrubqJQ0k5smcHEq09HMETSmh3TI',
    appId: '1:394544889657:android:6cda8e42efd34daafb32e8',
    messagingSenderId: '394544889657',
    projectId: 'fooddelivery-81c3c',
    storageBucket: 'fooddelivery-81c3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmqcv2zjskFE-yiErLyF0gvJQ7JE51EGU',
    appId: '1:394544889657:ios:c946cf4f152669dafb32e8',
    messagingSenderId: '394544889657',
    projectId: 'fooddelivery-81c3c',
    storageBucket: 'fooddelivery-81c3c.appspot.com',
    iosClientId: '394544889657-n86ptj3f9qb4hqf202af4nmkug6itna0.apps.googleusercontent.com',
    iosBundleId: 'com.maxonflutter.ecommerce',
  );
}
